//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AplikacjaInzynierska
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DataMKontPracZlecenie : DbContext
    {
        public DataMKontPracZlecenie()
            : base("name=DataMKontPracZlecenie")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Kontrahent_Zleceniodawca> Kontrahent_Zleceniodawca { get; set; }
        public DbSet<Pracownik> Pracownik { get; set; }
        public DbSet<Zlecenie> Zlecenie { get; set; }
    }
}
