//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AplikacjaInzynierska
{
    using System;
    using System.Collections.Generic;
    
    public partial class Kontrahent_Zleceniodawca
    {
        public Kontrahent_Zleceniodawca()
        {
            this.Zlecenie = new HashSet<Zlecenie>();
        }
    
        public decimal ID_KZ { get; set; }
        public bool Czy_kontrahent { get; set; }
        public string Imie_KZ { get; set; }
        public string Nazwisko_KZ { get; set; }
        public string NazwaFirmy { get; set; }
        public decimal NIP { get; set; }
        public decimal REGON { get; set; }
        public decimal Numer_Telefonu { get; set; }
        public string Adres_Email { get; set; }
    
        public virtual ICollection<Zlecenie> Zlecenie { get; set; }
    }
}
